<ol>
<?php 
    $items = $this->getItems(); 
    list($from, $to) = explode(',', $items[0]->getValueString());
   
    if ($from < 0.01) {
        $from = $this->__('From');
    } else  {
        $from = round($from);    
    }
       
    if ($to < 0.01) {
        $to = $this->__('To');
    } else {
        $to = round($to);    
    }
    
?>
<li class="mullayenav_range_input">
<input class="input-text mullayenav_range_from" type="text" maxlength="12" size="4" id="price_range_from---<?php echo $this->_filter->getRequestVar()?>" value="<?php echo $from?>" onclick="if(this.value==this.name) this.value='';"  name="<?php echo $this->__('From')?>"  style="background-color:#ffffff !important;"/>
<span class="mullayenav_range_dash">-</span>
<input class="input-text mullayenav_range_to" type="text" maxlength="12" size="4" id="price_range_to---<?php echo $this->_filter->getRequestVar()?>" value="<?php echo $to?>" onclick="if(this.value==this.name) this.value='';" name="<?php echo $this->__('To')?>"  style="background-color:#ffffff !important;"/>
<button type="button" class="button mullayenav_range_btn" id="price_button_go---<?php echo $this->_filter->getRequestVar()?>"><span><?php echo $this->__('Go')?></span></button>
</li>
</ol>
<input type="hidden" value="<?php echo $this->_filter->getRequestVar()?>" class="price-input">
